import { useState } from "react";
import { X, Search, ChevronRight, ChevronDown, BookOpen, Upload, Zap, Shield, Settings, HelpCircle, Mail, FileEdit, MessageCircle, History, Globe } from "lucide-react";
import { DARK, LIGHT, SUPPORT_EMAIL } from "../theme.js";

const SECTIONS = [
  {
    icon: Upload, label: "Getting Started", color: "#4f6ef7", darkBg: "#0d1233", lightBg: "#eef0ff",
    articles: [
      {
        title: "How to upload and analyze a document",
        content: `LegalEase AI supports PDF files up to 20 MB.

1. Go to the Analyzer page from the top navigation bar.
2. Drag and drop a PDF onto the drop zone, or click "Browse Files" to pick one.
3. Once uploaded, your file name and size appear in the preview row.
4. Select an Analysis Depth — Standard, Detailed, or Expert — from the dropdown.
5. Click "Analyze Document" — Groq LLaMA 3.1 will process your file in seconds.
6. Results appear across 4 tabs: Summary · Pros & Cons · Legal Terms · Clause Checker.

Only PDF files are supported. The backend uses pdfplumber to extract text, so scanned image-only PDFs may produce incomplete results.`,
      },
      {
        title: "Downloading your analysis report",
        content: `After analysis completes you will see a "Download Report" button in the results header bar.

Clicking it downloads a PDF report containing:
• File name and analysis date
• Risk Score and Risk Level (with animated gauge)
• Full AI Summary
• Favorable Clauses list
• Risks & Red Flags list
• Legal Terms Explained
• Clause-by-Clause report with Fair / Risk labels

The file saves automatically to your Downloads folder. You can also re-download any past report from the History page.`,
      },
      {
        title: "Creating a legal document with Draft Studio",
        content: `The Drafts page lets you generate professional legal documents from templates — no legal expertise needed.

1. Click "Drafts" in the top navigation.
2. Choose a template: Residential Lease, Commercial Lease, Sale Agreement, Land Deed, NDA, Power of Attorney, and more.
3. Fill in the required fields (landlord/tenant names, property address, rent, deposit, dates, state, etc.).
4. The document preview updates in real time as you type.
5. Add Custom Sections to insert your own clauses.
6. Click "AI Analysis" to instantly risk-score your draft before finalizing.
7. Download as PDF or DOCX, or send a Sign Request via email.

All templates are structured for Indian law but jurisdiction can be changed in Settings.`,
      },
      {
        title: "Sending a document for e-signature",
        content: `After generating a draft document you can send a sign request directly from the Draft Studio.

1. Click "Send Sign Request" in the draft actions panel.
2. Enter the recipient's name and email address.
3. LegalEase AI emails the document with a signing link.
4. You receive a confirmation notification once the request is sent.

The email service is powered by the backend email_service module. Ensure your account has a verified email.`,
      },
    ],
  },
  {
    icon: Zap, label: "Understanding Results", color: "#d97706", darkBg: "#1f1808", lightBg: "#fffbeb",
    articles: [
      {
        title: "What is the Risk Score?",
        content: `The Risk Score (0–100) is calculated from the number and severity of problematic clauses detected by Groq AI.

• 0–34   Low Risk    — The agreement is mostly fair.
• 35–64  Medium Risk — Some clauses need attention before signing.
• 65–100 High Risk   — Multiple red flags; consult a lawyer.

The score is shown as an animated SVG gauge in the results header. It is derived from the actual Groq LLaMA 3.1 output — weighted by the count and severity of cons versus pros. It is a guide, not a legal verdict.`,
      },
      {
        title: "Choosing an Analysis Depth",
        content: `Before analyzing, you can select one of three depth levels:

Standard — Focuses on the 5–8 most important clauses. Best for a quick overview. Processes up to 12,000 characters.

Detailed — Covers all significant clauses with section references. 8–12 paragraph summary. Processes up to 15,000 characters.

Expert — Exhaustive analysis: every clause, negotiation leverage points, missing standard clauses, and Indian property law compliance. 12–18 paragraph summary. Processes up to 18,000 characters.

Choose Expert for high-value or complex agreements. Standard is sufficient for standard residential leases.`,
      },
      {
        title: "Summary tab",
        content: `The Summary tab shows a plain-English overview of the document generated by Groq AI.

Below the summary, three quick-stat cards show:
• Risk Level — Low / Medium / High classification
• Good Clauses — count of clauses rated Fair
• Risk Clauses — count of clauses flagged as problematic

The depth and length of the summary varies based on the Analysis Depth you selected.`,
      },
      {
        title: "Pros & Cons tab",
        content: `This tab splits the AI output into two sections:

Favorable Clauses (green) — terms that protect or benefit you, such as capped rent escalation or clear maintenance splits.

Risks & Red Flags (red) — terms that could harm you, such as high late-payment penalties, missing arbitration clauses, or unreasonable termination conditions.

All items come directly from the Groq analysis of your specific document.`,
      },
      {
        title: "Legal Terms tab",
        content: `Legal documents contain jargon. This tab lists every complex term Groq AI identified in your document with a plain-English explanation and, in Expert mode, the relevant statutory section reference.

Examples it might find:
• Indemnification — agreeing to cover the landlord's legal costs
• Force Majeure — emergency clause protecting both parties
• Estoppel Certificate — a document you sign confirming lease facts

These explanations are generated from your actual document, not a generic glossary.`,
      },
      {
        title: "Clause Checker tab",
        content: `The Clause Checker lists every key clause from your document with a status label:

✓ Fair   — The clause is within normal limits.
✗ Risk   — This clause needs renegotiation before signing.

Each row shows the clause title and a brief explanatory note. This gives you a structured checklist to go through with your lawyer or landlord.

In Expert depth, the Clause Checker also includes negotiation suggestions — proposed replacement wording for risky clauses.`,
      },
    ],
  },
  {
    icon: FileEdit, label: "Draft Studio", color: "#7c3aed", darkBg: "#150e2a", lightBg: "#f5f3ff",
    articles: [
      {
        title: "Available document templates",
        content: `LegalEase AI includes ready-to-fill templates for the most common Indian legal agreements:

🏠 Residential Lease Agreement — Standard rental for flats, houses, independent floors.
🏢 Commercial Lease Agreement — Office, shop, or warehouse rental.
🤝 Sale Agreement (Agreement to Sell) — Pre-sale MOU for property purchase.
📜 Sale Deed — Final property transfer document.
🌾 Land Lease Agreement — Agricultural or vacant land rental.
🏗️ Joint Development Agreement — Builder-landowner JDA.
🔒 Non-Disclosure Agreement (NDA) — Confidentiality agreement.
✍️ Power of Attorney (General) — Authorization to act on someone's behalf.

Each template auto-fills today's date and is structured for the chosen Indian state's legal framework.`,
      },
      {
        title: "Adding custom sections to a draft",
        content: `Beyond the standard template fields, you can insert your own clauses:

1. Scroll to the "Custom Sections" area in the draft editor.
2. Click "Add Section" and enter a section title and content.
3. Reorder sections by dragging the grip handle.
4. Delete any section with the trash icon.

Custom sections are appended after the standard template clauses in the final document.`,
      },
      {
        title: "Running AI analysis on your draft",
        content: `Before downloading or sending your drafted document, run AI Analysis to check it for risks:

1. Click "AI Analysis" in the draft actions panel.
2. LegalEase AI sends the draft text to Groq and returns a risk assessment.
3. Review the risk score, pros, and cons — same format as the Document Analyzer.

This lets you catch any unintentionally unfair clauses in your own document before it's shared.`,
      },
    ],
  },
  {
    icon: History, label: "History", color: "#0284c7", darkBg: "#0b1929", lightBg: "#eff6ff",
    articles: [
      {
        title: "Viewing past analyses",
        content: `Every document you analyze is automatically saved to the History tab.

Each entry shows:
• Document name and file size
• Risk Score and Risk Level badge
• Date analyzed

Click any row to open the full detail panel on the right — including the complete summary, pros, cons, legal terms, and clause checker from that analysis.

You can also re-download the PDF report for any past analysis from the detail panel.`,
      },
      {
        title: "Starring and searching history",
        content: `Organize your history with these tools:

⭐ Star — Click the star icon on any document to bookmark it for quick access. Starred documents appear at the top.

🔍 Search — Use the search bar to filter by document name.

🗑️ Delete — Hover over any row and click the trash icon to remove it. Or go to Settings → Danger Zone → Delete All to clear everything at once.

Your analysis history and drafted documents are stored separately — use the tabs at the top of the History page to switch between them.`,
      },
    ],
  },
  {
    icon: MessageCircle, label: "AI Chat Assistant", color: "#16a34a", darkBg: "#0e1f14", lightBg: "#f0fdf4",
    articles: [
      {
        title: "Using the floating chat widget",
        content: `A floating AI chat assistant is available on the Home, Analyzer, Drafts, and Laws pages (look for the chat bubble in the bottom-right corner).

The assistant is context-aware:
• On the Analyzer page — it knows your uploaded document and analysis results, so you can ask "What are the main risks?" or "Explain the termination clause."
• On the Drafts page — it knows your current draft content and can help you improve clauses.
• On the Laws page — it can answer questions about Indian property law.
• On the Home page — it gives general guidance on LegalEase AI features.

You can also upload a document directly inside the chat for a focused discussion.`,
      },
      {
        title: "Quick question prompts",
        content: `When you open the chat, you'll see quick-action suggestions:

• "What are the main risks in this document?"
• "Explain the termination clauses"
• "Is this agreement fair for the tenant?"
• "What should I negotiate before signing?"

Tap any of these to send them instantly. You can also type any custom question in the input field.`,
      },
    ],
  },
  {
    icon: Globe, label: "Laws & Resources", color: "#f59e0b", darkBg: "#1f1508", lightBg: "#fef3c7",
    articles: [
      {
        title: "Browsing Indian property laws",
        content: `The Laws page provides a searchable reference library of Indian property legislation and rental regulations.

You can filter by state to see region-specific rules — covering all major Indian states including Tamil Nadu, Karnataka, Maharashtra, Delhi (NCT), Kerala, and more.

Use the AI Chat widget on this page to ask plain-English questions about any law or regulation.`,
      },
    ],
  },
  {
    icon: Shield, label: "Privacy & Security", color: "#ef4444", darkBg: "#1f0d0d", lightBg: "#fff0f0",
    articles: [
      {
        title: "Is my document stored on your servers?",
        content: `No. Your PDF is sent to the backend, text is extracted in-memory using pdfplumber, and only the extracted text is forwarded to Groq AI.

The file itself is never written to disk. The text is discarded immediately after Groq returns the analysis. Nothing from your document is logged or retained on our servers.`,
      },
      {
        title: "Who processes my document?",
        content: `Text extraction is done locally by the FastAPI backend using pdfplumber. The extracted text is sent to Groq's API (LLaMA 3.1 model) for analysis.

Groq's data handling policies apply to that portion. We recommend not uploading documents containing highly sensitive personal information (e.g. Aadhaar numbers, bank details) unless you have reviewed Groq's privacy policy.`,
      },
      {
        title: "Where is my history stored?",
        content: `Your analysis history and drafted documents are stored locally in your browser's localStorage — not on any server.

This means:
• Your data stays on your device.
• Clearing browser data will erase your history.
• History does not sync across devices.

You can export all your data as JSON from Settings → Data & Privacy → Export My Data.`,
      },
    ],
  },
  {
    icon: Settings, label: "Settings & Account", color: "#6b7280", darkBg: "#1a1c22", lightBg: "#f3f4f6",
    articles: [
      {
        title: "How do I change the analysis jurisdiction?",
        content: `Go to Settings → AI Preferences → Legal Jurisdiction.

Choose from India, USA, UK, or UAE. This tells the AI which legal norms to apply when flagging clauses — for example, a 3-month security deposit is standard in India but may differ elsewhere.`,
      },
      {
        title: "Auto-Analyze on Upload",
        content: `Go to Settings → AI Preferences → Auto-Analyze on Upload.

When enabled, LegalEase AI begins analyzing your document immediately after the file is uploaded — no need to click "Analyze Document" manually. Useful if you always want instant results.`,
      },
      {
        title: "Notification preferences",
        content: `Go to Settings → Notifications → In-App Notifications.

When enabled, the bell icon in the top-right shows real-time alerts for:
• Analysis completions (with risk score)
• High-risk document warnings
• Report download confirmations
• Sign request confirmations

Disable this if you prefer a distraction-free experience.`,
      },
      {
        title: "How do I update my name or password?",
        content: `Go to Settings → Account.

• Display Name — Edit your name and click Save.
• Change Password — Enter your current password, then your new password twice, and click Update Password.

Your email address cannot be changed after registration.`,
      },
      {
        title: "How do I delete my history?",
        content: `Go to Settings → Danger Zone → Delete All History.

This permanently clears all documents shown in the History tab. Individual items can also be deleted by hovering over a row in the History page and clicking the trash icon.

Note: This action cannot be undone. Export your data first if you want a backup (Settings → Data & Privacy → Export My Data).`,
      },
    ],
  },
];

function Article({ article, dark }) {
  const D = dark ? DARK : LIGHT;
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-xl border overflow-hidden" style={{ borderColor: D.border }}>
      <button onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3.5 text-left transition-colors"
        style={{ background: D.surface }}
        onMouseEnter={e => e.currentTarget.style.background = D.surfaceAlt}
        onMouseLeave={e => e.currentTarget.style.background = D.surface}>
        <span className="text-sm font-semibold" style={{ color: D.text }}>{article.title}</span>
        {open
          ? <ChevronDown size={14} style={{ color: D.textMuted }} />
          : <ChevronRight size={14} style={{ color: D.textMuted }} />}
      </button>
      {open && (
        <div className="px-4 pb-4 pt-2 space-y-1" style={{ background: D.surfaceAlt, borderTop: `1px solid ${D.border}` }}>
          {article.content.split("\n").map((line, i) => (
            <p key={i} className="text-xs leading-relaxed" style={{ color: D.textMuted, minHeight: line === "" ? 8 : undefined }}>
              {line || ""}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

export default function HelpDocsPage({ dark, onClose }) {
  const [search, setSearch]         = useState("");
  const [activeSection, setSection] = useState(null);
  const D = dark ? DARK : LIGHT;

  const filtered = SECTIONS.map(s => ({
    ...s,
    articles: s.articles.filter(a =>
      !search ||
      a.title.toLowerCase().includes(search.toLowerCase()) ||
      a.content.toLowerCase().includes(search.toLowerCase())
    ),
  })).filter(s => !search || s.articles.length > 0);

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.65)", backdropFilter: "blur(10px)" }}
      onClick={onClose}>
      <div onClick={e => e.stopPropagation()}
        style={{
          background: D.bg, border: `1px solid ${D.border}`,
          animation: "modalIn .3s cubic-bezier(.16,1,.3,1) forwards",
          width: "100%", maxWidth: 700, maxHeight: "88vh",
        }}
        className="rounded-3xl shadow-2xl flex flex-col overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 flex-shrink-0"
          style={{ background: D.surface, borderBottom: `1px solid ${D.border}` }}>
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl flex items-center justify-center"
              style={{ background: dark ? "#0d1233" : "#eef0ff" }}>
              <BookOpen size={15} style={{ color: "#4f6ef7" }} />
            </div>
            <div>
              <p className="font-bold text-sm" style={{ color: D.text }}>Help & Documentation</p>
              <p className="text-xs" style={{ color: D.textMuted }}>Everything you need to use LegalEase AI</p>
            </div>
          </div>
          <button onClick={onClose}
            className="w-8 h-8 rounded-xl flex items-center justify-center hover:opacity-70"
            style={{ background: D.surfaceAlt, color: D.textMuted }}>
            <X size={14} />
          </button>
        </div>

        {/* Search */}
        <div className="px-6 py-4 flex-shrink-0" style={{ borderBottom: `1px solid ${D.border}`, background: D.surface }}>
          <div className="flex items-center gap-2.5 px-4 py-2.5 rounded-xl border"
            style={{ background: D.surfaceAlt, borderColor: D.border }}>
            <Search size={13} style={{ color: D.textSubtle }} />
            <input className="bg-transparent outline-none text-sm flex-1" style={{ color: D.text }}
              placeholder="Search articles…" value={search} onChange={e => setSearch(e.target.value)} />
          </div>
        </div>

        {/* Body */}
        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar */}
          <div className="w-48 flex-shrink-0 overflow-y-auto p-3"
            style={{ borderRight: `1px solid ${D.border}`, background: D.surface }}>
            {SECTIONS.map(s => (
              <button key={s.label}
                onClick={() => setSection(activeSection === s.label ? null : s.label)}
                className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs font-semibold text-left transition-all mb-1"
                style={activeSection === s.label
                  ? { background: dark ? "#0d1233" : "#eef0ff", color: "#4f6ef7" }
                  : { color: D.textMuted, background: "transparent" }}
                onMouseEnter={e => { if (activeSection !== s.label) e.currentTarget.style.background = D.surfaceAlt; }}
                onMouseLeave={e => { if (activeSection !== s.label) e.currentTarget.style.background = "transparent"; }}>
                <div className="w-6 h-6 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: dark ? s.darkBg : s.lightBg }}>
                  <s.icon size={12} style={{ color: s.color }} />
                </div>
                {s.label}
              </button>
            ))}
          </div>

          {/* Articles */}
          <div className="flex-1 overflow-y-auto p-5 space-y-6">
            {filtered.length === 0 ? (
              <div className="text-center py-16">
                <HelpCircle size={28} style={{ color: D.textSubtle, margin: "0 auto 12px" }} />
                <p className="text-sm" style={{ color: D.textMuted }}>No articles match your search</p>
              </div>
            ) : filtered
                .filter(s => !activeSection || s.label === activeSection)
                .map(s => (
                  <div key={s.label}>
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-6 h-6 rounded-lg flex items-center justify-center"
                        style={{ background: dark ? s.darkBg : s.lightBg }}>
                        <s.icon size={12} style={{ color: s.color }} />
                      </div>
                      <p className="text-xs font-bold uppercase tracking-wider" style={{ color: D.textSubtle }}>{s.label}</p>
                    </div>
                    <div className="space-y-2">
                      {s.articles.map(a => <Article key={a.title} article={a} dark={dark} />)}
                    </div>
                  </div>
                ))}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-3.5 flex-shrink-0"
          style={{ background: D.surface, borderTop: `1px solid ${D.border}` }}>
          <p className="text-xs" style={{ color: D.textMuted }}>Can't find what you need?</p>
          <a href={`mailto:${SUPPORT_EMAIL}`}
            className="flex items-center gap-1.5 text-xs font-semibold hover:opacity-70 transition-opacity"
            style={{ color: "#4f6ef7" }}>
            <Mail size={12} /> {SUPPORT_EMAIL}
          </a>
        </div>
      </div>
    </div>
  );
}