import { Bell, CheckCircle, AlertTriangle, AlertCircle, FileText, X, Info } from "lucide-react";
import { DARK, LIGHT } from "../theme.js";

// Notifications are passed in from App.jsx and generated by real user actions.
// Nothing is predefined here.

function relativeTime(date) {
  const diff = Math.floor((Date.now() - new Date(date).getTime()) / 1000);
  if (diff < 60)    return "just now";
  if (diff < 3600)  return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

const TYPE_META = {
  success: { icon: CheckCircle, color: "#4ade80", darkBg: "#0e2a1a", lightBg: "#dcfce7" },
  risk:    { icon: AlertTriangle, color: "#f87171", darkBg: "#2a0d0d", lightBg: "#fee2e2" },
  warn:    { icon: AlertCircle,   color: "#fbbf24", darkBg: "#1f1508", lightBg: "#fef3c7" },
  info:    { icon: Info,           color: "#60a5fa", darkBg: "#0d1a33", lightBg: "#dbeafe" },
  doc:     { icon: FileText,       color: "#a78bfa", darkBg: "#150e2a", lightBg: "#f5f3ff" },
};

export default function NotificationsPanel({ dark, notifications, setNotifications, onClose }) {
  const D = dark ? DARK : LIGHT;

  const markAllRead = () => setNotifications(p => p.map(n => ({ ...n, read: true })));
  const dismiss     = (id) => setNotifications(p => p.filter(n => n.id !== id));
  const markRead    = (id) => setNotifications(p => p.map(n => n.id === id ? { ...n, read: true } : n));

  const unread = notifications.filter(n => !n.read).length;

  return (
    <div className="fixed inset-0 z-[160] flex items-start justify-end pt-[54px]" onClick={onClose}>
      <div onClick={e => e.stopPropagation()}
        style={{
          background: D.surface,
          borderLeft: `1px solid ${D.border}`,
          borderBottom: `1px solid ${D.border}`,
          animation: "slideIn .25s ease forwards",
          width: 390, maxHeight: "calc(100vh - 54px)",
        }}
        className="flex flex-col shadow-2xl overflow-hidden rounded-bl-2xl">

        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 flex-shrink-0"
          style={{ borderBottom: `1px solid ${D.border}` }}>
          <div className="flex items-center gap-2.5">
            <Bell size={16} style={{ color: "#4f6ef7" }} />
            <span className="font-bold text-sm" style={{ color: D.text }}>Notifications</span>
            {unread > 0 && (
              <span className="px-2 py-0.5 rounded-full text-xs font-bold"
                style={{ background: "#4f6ef7", color: "#fff" }}>{unread}</span>
            )}
          </div>
          <div className="flex items-center gap-2">
            {unread > 0 && (
              <button onClick={markAllRead}
                className="text-xs font-semibold px-2.5 py-1 rounded-lg hover:opacity-70 transition-opacity"
                style={{ color: "#4f6ef7", background: dark ? "#0d1233" : "#eef0ff" }}>
                Mark all read
              </button>
            )}
            <button onClick={onClose}
              className="w-7 h-7 rounded-lg flex items-center justify-center hover:opacity-70"
              style={{ background: D.surfaceAlt, color: D.textMuted }}>
              <X size={13} />
            </button>
          </div>
        </div>

        {/* List */}
        <div className="flex-1 overflow-y-auto">
          {notifications.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 gap-3">
              <div className="w-14 h-14 rounded-2xl flex items-center justify-center"
                style={{ background: dark ? "#1c2230" : "#f0f2f5" }}>
                <Bell size={24} style={{ color: D.textSubtle }} />
              </div>
              <p className="text-sm font-semibold" style={{ color: D.text }}>All caught up!</p>
              <p className="text-xs text-center px-8" style={{ color: D.textMuted }}>
                Notifications will appear here when you analyze documents.
              </p>
            </div>
          ) : notifications.map(n => {
            const meta = TYPE_META[n.type] || TYPE_META.info;
            const Icon = meta.icon;
            return (
              <div key={n.id}
                onClick={() => markRead(n.id)}
                className="flex gap-3 px-5 py-4 cursor-pointer transition-colors"
                style={{
                  borderBottom: `1px solid ${D.borderLight}`,
                  background: n.read ? "transparent" : (dark ? "rgba(79,110,247,0.05)" : "rgba(79,110,247,0.03)"),
                }}
                onMouseEnter={e => e.currentTarget.style.background = D.surfaceAlt}
                onMouseLeave={e => e.currentTarget.style.background = n.read ? "transparent" : (dark ? "rgba(79,110,247,0.05)" : "rgba(79,110,247,0.03)")}>

                <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5"
                  style={{ background: dark ? meta.darkBg : meta.lightBg }}>
                  <Icon size={15} style={{ color: meta.color }} />
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <p className="text-xs font-bold leading-snug" style={{ color: D.text }}>{n.title}</p>
                    {!n.read && <span className="w-2 h-2 rounded-full flex-shrink-0 mt-1" style={{ background: "#4f6ef7" }} />}
                  </div>
                  <p className="text-xs leading-relaxed mt-1" style={{ color: D.textMuted }}>{n.body}</p>
                  <div className="flex items-center justify-between mt-2">
                    <span className="text-xs" style={{ color: D.textSubtle }}>{relativeTime(n.time)}</span>
                    <button onClick={e => { e.stopPropagation(); dismiss(n.id); }}
                      className="text-xs hover:opacity-70 transition-opacity" style={{ color: D.textSubtle }}>
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {notifications.length > 0 && (
          <div className="px-5 py-3 flex-shrink-0 flex items-center justify-between"
            style={{ borderTop: `1px solid ${D.border}` }}>
            <p className="text-xs" style={{ color: D.textSubtle }}>{notifications.length} notification{notifications.length !== 1 ? "s" : ""}</p>
            <button onClick={() => setNotifications([])}
              className="text-xs font-semibold hover:opacity-70 transition-opacity"
              style={{ color: "#f87171" }}>
              Clear all
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
